### ISSUE TITLE
How to run any example code, and have u tested in real time market if so what was the accuracy

### ISSUE THREAD

**Issue by raviyellani** [mayank-bharwal/Intraday-GARCH-strategy-in-Python#1]
any example to test

**Comment by bharwalmayank** [comment]
Hey Ravi, Thanks for taking interest in this.
No I haven't tested this project using a real time market API and I am still working on it. I was reading a book about portfolio optimization and decided to sandbox a program out of it. I am more than willing to take any suggestions or answer your questions about this project.
